version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    container_name: adaptive_testing
    command: python ./manage.py runserver 0.0.0.0:8000
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure