# Generated by Django 4.0.4 on 2022-04-28 13:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=3000, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно или нет')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(default='Unknown', max_length=300, unique=True, verbose_name='Название компетенции')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', help_text='Текст вопроса', max_length=3000, verbose_name='Вопрос')),
                ('type', models.CharField(blank=True, choices=[('1', 'Один ответ'), ('2', 'Несколько ответов')], default=1, help_text='Тип вопроса', max_length=1)),
                ('level', models.ForeignKey(help_text='Сложность вопроса', on_delete=django.db.models.deletion.CASCADE, to='Testing.levels')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(related_name='user_answer', to='Testing.answers')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='Testing.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название темы', max_length=500, verbose_name='Название темы')),
                ('competence', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='competence_theme', to='Testing.competence')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='Время теста')),
                ('answers_pass_value', models.IntegerField(default=0, verbose_name='Количество вопросов для перехода на следующий уровень')),
                ('next_level_score', models.IntegerField(default=0, verbose_name='Количество баллов для перехода на следующий уровень')),
                ('level', models.ForeignKey(default=2, help_text='Начальный уровень сложности', on_delete=django.db.models.deletion.CASCADE, related_name='start_level', to='Testing.levels')),
                ('question', models.ManyToManyField(related_name='testing_question', to='Testing.questions')),
                ('themes', models.ManyToManyField(default=None, help_text='Набор тем для теста', related_name='themes', to='Testing.themes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='theme',
            field=models.ForeignKey(help_text='Тема вопроса', on_delete=django.db.models.deletion.CASCADE, to='Testing.themes'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(default='Unknown', max_length=150, verbose_name='Должность сотрудника')),
                ('phone_number', models.CharField(default='Unknown', max_length=12, unique=True, verbose_name='Номер телефона')),
                ('address', models.CharField(default='Unknown', max_length=150, verbose_name='Адрес сотрудника')),
                ('current_level', models.ForeignKey(on_delete=models.SET(2), to='Testing.levels')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка на курс')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='Testing.levels')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='Testing.themes')),
            ],
            options={
                'verbose_name': 'Курс для повышения квалификации',
                'verbose_name_plural': 'Курсы для повышения квалификации',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Testing.questions'),
        ),
    ]
