# Generated by Django 4.0 on 2021-12-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Testing.questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.ForeignKey(help_text='Сложность вопроса', on_delete=django.db.models.deletion.CASCADE, to='Testing.levels'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='theme',
            field=models.ForeignKey(help_text='Тема вопроса', on_delete=django.db.models.deletion.CASCADE, to='Testing.themes'),
        ),
    ]
