# Generated by Django 4.0.4 on 2022-11-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsettings',
            old_name='competence',
            new_name='competence_id',
        ),
        migrations.RenameField(
            model_name='testsettings',
            old_name='level',
            new_name='level_id',
        ),
    ]
