# Generated by Django 4.0.4 on 2022-10-05 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User id', models.IntegerField(help_text='Айди юзер')),
                ('Updated date', models.DateTimeField(default=datetime.datetime(2022, 10, 5, 19, 50, 53, 359348))),
                ('Question summary', models.IntegerField(help_text='Всего вопросов')),
                ('Wrong questions', models.IntegerField(help_text='Количество неправильно отвеченных вопросов')),
                ('Skipped question summary', models.IntegerField(help_text='Всего пропущенных вопросов', null=True)),
                ('Time summary', models.DurationField(help_text='Всего времени', null=True)),
                ('Time spent', models.DurationField(help_text='Затраченное время', null=True)),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
            },
        ),
    ]
