# Generated by Django 4.0.4 on 2022-11-10 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0002_rename_competence_testsettings_competence_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingresult',
            name='competence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Testing.competence'),
        ),
    ]
