# Generated by Django 4.0.4 on 2022-10-05 16:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Testing', '0002_testingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingresult',
            name='User id',
        ),
        migrations.AddField(
            model_name='testingresult',
            name='user_id',
            field=models.ForeignKey(help_text='User ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_level',
            field=models.ForeignKey(default=2, on_delete=models.SET(2), to='Testing.levels'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='Question summary',
            field=models.IntegerField(help_text='All questions count'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='Skipped question summary',
            field=models.IntegerField(help_text='Skipped questions count', null=True),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='Time spent',
            field=models.DurationField(help_text='Time spent', null=True),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='Time summary',
            field=models.DurationField(help_text='Estimated Time', null=True),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='Updated date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 16, 57, 1, 183516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='Wrong questions',
            field=models.IntegerField(help_text='Wrong answers count'),
        ),
    ]
