# Generated by Django 4.0.4 on 2022-10-05 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0003_remove_testingresult_user id_testingresult_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testingresult',
            old_name='Question summary',
            new_name='question_summary',
        ),
        migrations.RenameField(
            model_name='testingresult',
            old_name='Skipped question summary',
            new_name='skipped_question_summary',
        ),
        migrations.RenameField(
            model_name='testingresult',
            old_name='Time spent',
            new_name='time_spent',
        ),
        migrations.RenameField(
            model_name='testingresult',
            old_name='Time summary',
            new_name='time_summary',
        ),
        migrations.RenameField(
            model_name='testingresult',
            old_name='Wrong questions',
            new_name='wrong_questions',
        ),
        migrations.RemoveField(
            model_name='testingresult',
            name='Updated date',
        ),
        migrations.AddField(
            model_name='testingresult',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
