# Generated by Django 4.0.4 on 2022-11-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_testingresult_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingresult',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.testsettings'),
        ),
    ]
