# Generated by Django 4.0.4 on 2022-11-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0004_testingresult_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingresult',
            name='time_spent',
            field=models.TimeField(help_text='Time spent', null=True),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='time_summary',
            field=models.TimeField(help_text='Estimated Time', null=True),
        ),
    ]
