# Generated by Django 4.0.4 on 2022-10-20 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0004_rename_question summary_testingresult_question_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='competence',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, related_name='competence_theme', to='Testing.competence'),
        ),
    ]
