# Generated by Django 4.0.4 on 2022-10-13 06:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Testing', '0004_rename_question summary_testingresult_question_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='Время теста')),
                ('answers_pass_value', models.IntegerField(default=0, verbose_name='Количество вопросов для перехода на следующий уровень')),
                ('next_level_score', models.IntegerField(default=0, verbose_name='Количество баллов для перехода на следующий уровень')),
                ('competence', models.ForeignKey(default='Unknown', help_text='Test Competence', on_delete=django.db.models.deletion.CASCADE, related_name='test_competence', to='Testing.competence')),
                ('level', models.ForeignKey(default=2, help_text='Начальный уровень сложности', on_delete=django.db.models.deletion.CASCADE, related_name='start_level', to='Testing.levels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Setting',
                'verbose_name_plural': 'Test Settings',
            },
        ),
        migrations.AddField(
            model_name='testingresult',
            name='answered_questions',
            field=models.CharField(help_text='Questions answered by user', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='question_summary',
            field=models.IntegerField(default=0, help_text='All questions count'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='skipped_question_summary',
            field=models.IntegerField(default=0, help_text='Skipped questions count', null=True),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='wrong_questions',
            field=models.IntegerField(default=0, help_text='Wrong answers count'),
        ),
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
