# Generated by Django 4.0.4 on 2022-10-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0006_testsettings_testingresult_answered_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsettings',
            name='questions_count',
            field=models.IntegerField(default=0, verbose_name='Questions in block count'),
        ),
    ]
