# Generated by Django 4.0.4 on 2022-10-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0006_testsettings_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='competence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Testing.competence'),
        ),
    ]
