# Generated by Django 4.0.4 on 2022-10-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0008_questions_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingresult',
            name='competence',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Testing.competence'),
        ),
        migrations.AddField(
            model_name='testingresult',
            name='level',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Testing.levels'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='competence',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='competence_theme', to='Testing.competence'),
        ),
    ]
