# Generated by Django 4.0.4 on 2022-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0010_alter_themes_competence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsettings',
            name='answers_pass_value',
        ),
        migrations.RemoveField(
            model_name='testsettings',
            name='user',
        ),
        migrations.AddField(
            model_name='testsettings',
            name='name',
            field=models.CharField(default='Test', max_length=200, verbose_name='Test name'),
        ),
    ]
